### ISSUE TITLE
Disable screen rotation

### ISSUE THREAD

**Issue by niosus** [petervojtek/touchless-map#1]
Hey, that is a pretty neat idea :) However, it is hardly usable if the screen is getting rotated when i tilt the phone :)

**Comment by petervojtek** [comment]
good point. 
here is fix to lock the screen into portrait mode: 6f097f639d3
some day later there may be an option in settings to choose if screen should be locked in portrait or landscape mode.

**Comment by niosus** [comment]
Thanks! Keep up the good work! :+1:
