### ISSUE TITLE
apk download

### ISSUE THREAD

**Issue by de-vries** [petervojtek/touchless-map#3]
Hi, I would like to try your app, but I can't find were I can download a apk file and there is no way I'm gonna let google services into my phone. Could you please provide a apk link, or even better, get your app on F-Droid?

**Comment by petervojtek** [comment]
hi de-vries,
here is the apk:
https://github.com/petervojtek/touchless-map/tree/master/releases

actually I tried to register to F-Droid but registration email has not arrived :(

**Comment by de-vries** [comment]
Thank you! 
first impression: nice app
